### PR TITLE
Make `realpath` canonicalize paths

### PR DESCRIPTION
**Pull request by studoot**
I've had a need for readlink to fill out absolute paths from relative ones, so have modified the implementation of realpath in mingw.c to a) canonicalize the path on Windows (with Win32 function GetFullPathName), and b) resolve symlinks with Win32 function GetFinalPathNameByHandle.

I've also modified the defconfigs for mingw32 and mingw64 to include readlink and realpath.

I've built this on Ubuntu 16.04 running under WSL on Windows 10, with version 5.3.1 of the mingw32 cross-toolchain.

### CODE REVIEW

**Comment by rmyorston** [comment]
I've reworked your code somewhat on the https://github.com/rmyorston/busybox-w32/tree/realpath branch.

I haven't enabled the ```readlink``` applet because, in the absence of a ```readlink(2)``` implementation, it doesn't do much more than ```realpath```. Git for Windows has an implementation of ```readlink(2)``` but I haven't yet convinced myself to pull it across.

**Comment by ale5000-git** [comment]
@rmyorston: Does it still work also if the filename use unicode chars and the user has disabled the "8.3 dos file names creation on NTFS partitions"?

**Comment by rmyorston** [comment]
I don't know. That's not the sort of thing I test.

**Comment by studoot** [comment]
That's fair enough (regarding the `readlink` applet)... I suspect the path canonicalisation function could be refactored to give a `readlink(2)` implementation - from my reading of the man page, `readlink(2)` just resolves a symlink, which is what your function `static char *resolve_symlinks(char *path)` does?

Anyway - `realpath` gets me what I was wanting (and also I've realised I was using `readlink -f` in my shell scripts where I should probably have been using `realpath` anyway, so I've learnt that as well...). And the other `readlink` use cases I've had (with the `-e` and `-m` flags) aren't pertinent to busybox.

**Comment by rmyorston** [comment]
My understanding is that ```readlink(2)``` simply returns the contents of the symlink. Unlike ```resolve_symlinks``` it doesn't resolve relative links.

**Comment by rmyorston** [comment]
Agreed on ```realpath``` being more useful than ```readlink```. I've just checked a major codebase of mine and the only instance of ```readlink``` I can see should actually be ```realpath```.

The one niggle I have with symlinks in busybox-w32 is that ```ls -l``` doesn't display them properly.  Then again, I don't know how widely symlinks are used in Windows.  Not very, I suspect.

**Comment by studoot** [comment]
In that case, I might just as well close this PR?

**Pull request closed without merging**
