### PR TITLE
ash.c lazy loading of APIs unavailable on nanoserver

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

Part of the changes required for busybox 64-bit to run on nanoserver
in a container on Windows.

Nanoserver does not support the full API surface of the windowsservercore
images. This change updates shell/ash.c so that the functions are lazily
loaded from kernel32 and do not cause busybox to quit when calling
an unsupported API.

The reason for this change (there are others in the pipeline) is to
support running docker CI on Windows using nanoserver as the base image.
Currently the CI servers at https://github.com/docker/docker use
windowsservercore. Docker makes extensive use of busybox for its
integration test suite. To move to nanoserver (which dramatically improves)
performance and allows the use of Hyper-V containers as well, we
need a 64-bit version of busybox which doesn't fail calling Win32 APIs
which aren't available in nanoserver.

### CODE REVIEW

**Comment by jhowardmsft** [comment]
@rmyorston Ron - I wasn't sure if I should be submitting this PR against this repo, or https://github.com/pclouds/busybox-w32. Happy to open over there if I guessed wrong 😇

**Comment by rmyorston** [comment]
This is probably the best place for your pull request.  pclouds has [stated](https://github.com/pclouds/busybox-w32/issues/21) that he's no longer actively developing busybox-w32.

I'll go out on a limb and say that both the noconsole option (which is what the affected code is about) and the requirement to run on nanoserver are fairly niche requirements.  How about, instead of throwing code at the problem, we just make the noconsole option configurable at build time?  Have a look at the noconsole branch in my repo.

**Comment by jhowardmsft** [comment]
@rmyorston Yes, indeed, that might work for this instance, but not for the other two places I've currently identified. The other two are:

Unicode support in termios.c: https://github.com/jhowardmsft/busybox-w32/commit/46fef01e13ac9038eda897a7792c8ed47f307bb1

winansi.c (I'm not quite sure what the right fix should be here - https://github.com/jhowardmsft/busybox-w32/commit/5289d205567d31ad1f203497f72981fb24923f32 is incomplete). However, with these three changes, busybox does seem to run in a nanoserver container (and on a nanoserver host).

**Comment by rmyorston** [comment]
After further reflection I've committed the change to make the noconsole option configurable, but with one alteration:  it's disabled by default for 64-bit builds, like yours for Nano Server.

32-bit users will be unaffected whether they use the binaries I provide or build their own.  64-bit users must always have created their own binaries (since I don't provide them) and if they're using the undocumented noconsole option they must have read the source.  If they can manage that they can change a compile time setting.  That's what they get for being too clever.

I need to ponder your other changes.

**Comment by ale5000-git** [comment]
@jhowardmsft: Have you tested the latest code?
Most of the problems should be already fixed I think.

**Comment by ale5000-git** [comment]
@jhowardmsft: Have you tested the latest code?
Most of the problems should be already fixed I think.

**Comment by lowenna** [comment]
@jstarks - Closing this, but not sure if anyone really wants to run busybox on nanoserver any more? If so, could someone rebase and carry? Thanks :)

**Pull request closed without merging**
