### PR TITLE
fixdep/kbuild fixes for building inside MSYS2

### PR DESCRIPTION
**Pull request by dscho**
So far, busybox-w32 builds on Linux, via cross-compilers, I guess.

The [MSYS2](https://msys2.github.io/) project (which is also used as a basis to run Git for Windows' Unix shell/Perl scripts and OpenSSH) provides a pretty complete infrastructure to build free software on Windows itself.

This Pull Request brings in changes required to make that happen. With this, `make mingw32_defconfig` should work in a regular MSYS2 setup.

### CODE REVIEW

**Comment by dscho** [comment]
This PR, BTW, is a test balloon, as I have [many more patches](https://github.com/rmyorston/busybox-w32/compare/master...dscho:msys2) I plan to use as a basis to ship a very small [MinGit for Windows](https://github.com/git-for-windows/git/wiki/MinGit).

Please let me know, therefore:
- whether you are interested at all,
- what you would like to see changed, and
- how you like your Pull Requests.

**Comment by rmyorston** [comment]
I've applied your patches with some changes.  There were a couple of things that broke cross-compilation on Linux :-(

* I defined ```O_BINARY``` in ```fixdep.c```
* I included ```stdint.h``` in ```zconf.tab.c_shipped``` to avoid complaints about ```intptr_t```

It's possible that my MSYS2 wasn't properly configured, but I had to ```#ifdef``` out the include of ```regex.h``` in ```symbol.c``` to get ```make mingw32_defconfig``` to work.

The revised patch to ```lkc.h``` is what the kernel uses.

I don't have any *particular* interest in getting busybox-w32 to build on MSYS2 or MinGit, but I'm happy to accept patches if they're useful to others.  (And if it doesn't result in too much extra work for me.)

Looking at your other patches I can see you're more fussy about compiler warnings than me. Where possible I prefer to keep differences from upstream BusyBox to a minimum.

I like pull requests that don't break my build ;-)  Otherwise I don't really care.  If I don't like them I'll just ignore them.

**Comment by dscho** [comment]
> I've applied your patches with some changes.

Thanks. I had hoped to check the checkbox that allows you to force-push into my branch so that you could merge the Pull Request after making those changes.

For future record, I am more than happy to change whatever you require changed in my Pull Requests.

> There were a couple of things that broke cross-compilation on Linux :-(

Ouch...

> I don't have any particular interest in getting busybox-w32 to build on MSYS2 or MinGit

To clarify, the build would be inside MSYS2, BusyBox would be *used* in MinGit.

**Comment by dscho** [comment]
> I like pull requests that don't break my build ;-)

Any indication how you build? I would like to test that locally (in my Linux VM) before opening the next PRs, to save roundtrips.

**Comment by rmyorston** [comment]
>Thanks. I had hoped to check the checkbox that allows you to force-push into my branch so that you could merge the Pull Request after making those changes.

Yeah, I'm not comfortable using GitHub to merge stuff.  I just do it by hand on the command line.

>Any indication how you build? I would like to test that locally (in my Linux VM) before opening the next PRs, to save roundtrips.

I use Fedora, currently the newly-released Fedora 26.  A Workstation installation from the Live image has *almost* everything required.  The only additional bits needed are the cross-compiler and some random perl documentation thingy, though the latter isn't essential.  These can be installed with the command ```dnf install mingw32-gcc perl-Pod-Html```.  After that fetch the busybox-w32 source and run ```make mingw32_defconfig && make```.

**Comment by dscho** [comment]
> > Thanks. I had hoped to check the checkbox that allows you to force-push into my branch so that you could merge the Pull Request after making those changes.
> 
> Yeah, I'm not comfortable using GitHub to merge stuff. I just do it by hand on the command line.

No problem. Just call `git push github.com:dscho/busybox-w32 +<branchname>` after rewriting the branch *before* pushing the merge.

> I use Fedora, currently the newly-released Fedora 26. A Workstation installation from the Live image has almost everything required. The only additional bits needed are the cross-compiler and some random perl documentation thingy, though the latter isn't essential. These can be installed with the command dnf install mingw32-gcc perl-Pod-Html. After that fetch the busybox-w32 source and run make mingw32_defconfig && make.

Okay. I should be able to rework that into something that does the job in my Ubuntu VM.

Thanks!

**Comment by dscho** [comment]
> > I use Fedora, currently the newly-released Fedora 26. A Workstation installation from the Live image has almost everything required. The only additional bits needed are the cross-compiler and some random perl documentation thingy, though the latter isn't essential. These can be installed with the command dnf install mingw32-gcc perl-Pod-Html. After that fetch the busybox-w32 source and run make mingw32_defconfig && make.
> 
> Okay. I should be able to rework that into something that does the job in my Ubuntu VM.

Turns out that this works on Ubuntu 6.04.2 LTS:

```sh
sudo apt install gcc-mingw-w64-i686
make mingw32_defconfig && make
```

**Pull request closed without merging**
